stages:
  - stage: Deployment
    displayName: Detection Rule Deployment
    dependsOn: Validation
    condition: | 
      or(eq(variables['Build.SourceBranchName'], variables['OpenTide.DefaultBranch']),
         eq(variables['Build.Reason'], 'Manual'),
         eq(variables['Build.Reason'], 'PullRequest')
        )
    jobs:
      - job: CheckForChanges
        displayName: 'Check for Detection Rules changes'
        steps:
          - template: ../templates/check_mdr_changes.yml

      - deployment: ProductionDeployment
        displayName: Deploy to Production
        environment: $(OpenTide.Deployment.Environment.Production)
        dependsOn: CheckForChanges
        condition: |
          and(eq(dependencies.CheckForChanges.outputs['FilesChanged.ChangesDetected'], 'true'),
              or(eq(variables['Build.SourceBranchName'], variables['OpenTide.DefaultBranch']),
                 eq(variables['Build.Reason'], 'Manual')
                 )
            )
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../jobs/deployment.production.yml

      - deployment:  StagingDeployment
        displayName: Deploy to Staging
        dependsOn: CheckForChanges
        environment: $(OpenTide.Deployment.Environment.Staging)
        condition:
          and(eq(dependencies.CheckForChanges.outputs['FilesChanged.ChangesDetected'], 'true'),
              eq(variables['Build.Reason'], 'PullRequest')
              )
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../jobs/deployment.staging.yml