stages:
  - stage: Framework
    dependsOn: Validation
    jobs:

      - job: Framework
        displayName: Framework Generation
        condition: | 
          or(eq(variables['Build.SourceBranchName'], variables['OpenTide.DefaultBranch']),
             eq(variables['Build.Reason'], 'Manual')
             )
        steps:
          - template: ../jobs/framework.yml