import sys
import git
from dataclasses import dataclass
from typing import Optional, List

sys.path.append(str(git.Repo(".", search_parent_directories=True).working_dir))

from Engines.modules.logs import log
from Engines.modules.models import TideDefinitionsModels


@dataclass
class Objects:

    @dataclass
    class DetectionObjective:
        """Detection Objectives represent a modelling of detection opportunities
        against identified Threat Vectors"""

        @dataclass
        class Objective:
            """Describes a detection concept, alongside technical descriptions
            for precise detection opportunities called signals."""

            @dataclass
            class Signal:
                """Detailed, technical description of each detection opportunity, aligned
                with the overarching Detection Objectives. These signals can all be independent
                opportunities, or related within a larger higher-order detection strategy which
                can be documented under correlation."""

                @dataclass
                class Data:
                    """Modelling of the required data to implement the signal"""
                    availability: str  # Unknown, Not Available, Partial, Complete
                    """Represents whether the necessary data is already captured"""
                    requirements: str
                    """Technical details of the required data"""
                    logsources: Optional[List[str]] = None
                    """Existing, available logsources which cover the data requirements for the signal"""

                @dataclass
                class Detector:
                    """Detection existing in some toolings/platforms, but which does not exist as an OpenTide
                    Detection Rule, stored as-code. Useful to represent detectors, vendor detections, and
                    black-box capabilities documented by vendors but not necessarily fully controlled."""
                    name: str
                    """Name of the detector, either as documented by the vendor if available,
                    else close to the alerts generated by the tool."""
                    technology: str
                    """The technology/platform that provides this detection capability."""
                    description: str
                    """High level overview over the external detection capabilities"""
                    link: Optional[str] = None
                    """Link to relevant docs, if available, for the external detection"""

                @dataclass
                class Example:
                    """When available, relevant queries/detection rules already shared in open-source
                    repositories or vendor detection libraries"""
                    description: str
                    """High level overview of the detection example and its approach"""
                    link: str
                    """Link to the shared detection (github, blog post, vendor repository...)"""
                    language: Optional[str] = None
                    """When relevant, the language of the shared detection query"""
                    query: Optional[str] = None
                    """When relevant, the detection query that was shared"""

                name: str
                """Name of the Detection Signal - in general, this should be a good name
                for an alert."""
                uuid: str
                """A UUIDv4 to uniquely identify the Detection Signal."""
                description: str
                """Detailed, low level technical details allowing to transform this
                specification into Detection Rules."""
                severity: str  # Informational, Low, Medium, High, Critical
                """How critical this signal should be processed. In general, this should map closely
                to the alert severity that the detection rule would raise."""
                data: Data
                """Data requirements specification for this signal"""
                methodology: str
                """High level category of the type of detection approach that the signal specification is proposing."""
                entities: List[str]
                """Entities that the signal is using to perform its detection.
                Particularly useful to know for alert processing, entity grouping etc."""
                effort: Optional[int] = None  # 1-10
                """Rough estimate of the technical effort required. This is usually environment
                dependent based. From 1 to 10, 1 being a very quick action, 10 taking resources across several cycles."""
                detectors: Optional[List[Detector]] = None
                """References to external detection capabilities"""
                examples: Optional[List[Example]] = None
                """References to detection examples from open-source or vendor repositories"""
                parent: Optional[str] = None
                """Internal string which may be used to understand to which detection objective this signal ties into. Only used within index to keep track of sub objects."""

            @dataclass
            class Composition:
                """Models how the signals described should be used as part of a final
                detection implementation"""
                strategy: str
                """Describes how signals should be used - from fully synergetic, to fully separate"""
                description: str
                """Technical details about the recommended strategy"""

            priority: str  # Low, Medium, High, Critical
            """How important the detection objective is to implement"""
            type: str
            """Purpose of the Detection Objective"""
            description: str
            """High Level description of the Detection Objective goal and key concept.
            Technical description of different detection methodologies/signals must
            be done under signals."""
            signals: List[Signal]
            """Collection of detection signals that make up this objective"""
            composition: Composition
            """Strategy for composing multiple signals together"""
            investment: Optional[str] = None  # Minor, Moderate, Significant, Major
            """How much overall investment is expected in developing the detection objective
            capabilities. This may take in account larger problematics than the effort to implement
            signals using the `effort` keyword, for example when new log sources, tooling,
            or infrastructure is required."""
            threats: Optional[List[str]] = None
            """OpenTide Threat Vectors which are covered by this Detection Objective.
            Required when the objective type is "Threat", optional otherwise."""
            attack: Optional[List[str]] = None  # T\d{4} pattern
            """Optional, allows a more precise mapping of the ATT&CK techniques
            associated with the detection objectives. If not precised, the ATT&CK
            Techniques mapped by the related Threat Vectors must be considered instead."""

        name: str
        """Name of the OpenTide Detection Objective"""
        metadata: TideDefinitionsModels.TideObjectMetadata
        """Metadata about the detection objective"""
        objective: Objective
        """Core objective definition including signals and composition"""
        composition: Objective.Composition
        """Strategy for composing detection signals"""
        references: Optional[TideDefinitionsModels.TideObjectReferences] = None
        """Optional references for this detection objective"""
