"""Tests for GitHub Actions workflow rendering."""

from __future__ import annotations

from opentide.ci.github import render_github
from opentide.ci.models import CiRenderOptions


def test_render_github_includes_core_jobs() -> None:
    options = CiRenderOptions(
        ci="github",
        platforms=["sentinel", "crowdstrike"],
        default_branch="development",
        python_version="3.12",
    )
    workflow = render_github(options)
    assert "name: OpenTide" in workflow
    assert "validate:" in workflow
    assert "generate:" in workflow
    assert "deploy_production:" in workflow
    assert "document:" in workflow
    assert "branches:" in workflow
    assert "- development" in workflow
    assert "github.ref == 'refs/heads/development'" in workflow
    assert "format(" not in workflow


def test_render_github_validate_includes_query_platforms() -> None:
    options = CiRenderOptions(ci="github", platforms=["sentinel", "splunk"])
    workflow = render_github(options)
    assert "opentide validate query --platform sentinel --live" in workflow
    assert "opentide validate query --platform splunk --live" in workflow
    assert "skip sentinel live query validation" in workflow
    assert "skip splunk live query validation" in workflow
    validate = workflow.split("  validate:", 1)[1].split("  generate:", 1)[0]
    assert "AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}" in validate


def test_render_github_staging_job_when_enabled() -> None:
    options = CiRenderOptions(ci="github", staging=True)
    workflow = render_github(options)
    assert "deploy_staging:" in workflow
    assert "opentide deploy --dry-run --plan STAGING" in workflow
    assert "opentide deploy --plan STAGING --skip-unconfigured" in workflow
    assert "opentide validate --strict" in workflow
    assert "opentide lint --strict" in workflow
    assert "AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}" in workflow
    assert "OPENTIDE_SECRETS" not in workflow
    production = workflow.split("  deploy_production:", 1)[1].split("  document:", 1)[0]
    assert "needs: generate" in production
    assert "needs: deploy_staging" not in production
    assert "fetch-depth: 0" in production
    staging = workflow.split("  deploy_staging:", 1)[1].split("  deploy_production:", 1)[0]
    assert "fetch-depth: 0" in staging
    validate = workflow.split("  validate:", 1)[1].split("  generate:", 1)[0]
    assert "fetch-depth: 0" not in validate


def test_render_github_no_staging_skips_staging_job() -> None:
    options = CiRenderOptions(ci="github", staging=False, promotion=False)
    workflow = render_github(options)
    assert "deploy_staging:" not in workflow
    assert "needs: generate" in workflow


def test_render_github_inflight_job_when_enabled() -> None:
    options = CiRenderOptions(ci="github", inflight=True, default_branch="main")
    workflow = render_github(options)
    assert "inflight_shards:" in workflow
    assert "inflight_prune:" in workflow
    assert "opentide generate inflight" in workflow
    assert "opentide generate inflight prune" in workflow
    assert 'git push origin "HEAD:main"' in workflow


def test_render_github_no_inflight_skips_inflight_job() -> None:
    options = CiRenderOptions(ci="github", inflight=False)
    workflow = render_github(options)
    assert "inflight_shards:" not in workflow


def test_render_github_has_no_promote_job() -> None:
    """Promotion runs inside ``opentide deploy``, configured by ``deployment.toml``."""
    options = CiRenderOptions(ci="github", promotion=True, promotion_target="PRODUCTION")
    workflow = render_github(options)
    assert "promote:" not in workflow
    assert "opentide mutate promote" not in workflow


def test_render_github_sets_repo_root_without_optional_jobs() -> None:
    """Every generated workflow must export OPENTIDE_REPO_ROOT, even without explorer/inflight."""
    options = CiRenderOptions(ci="github", inflight=False, explorer_pages=False)
    workflow = render_github(options)
    preamble, _, jobs = workflow.partition("\njobs:")
    assert "OPENTIDE_REPO_ROOT: ${{ github.workspace }}" in preamble
    assert "OPENTIDE_REPO_ROOT" not in jobs
    assert "validate:" in workflow
    assert "generate:" in workflow
    assert "deploy_production:" in workflow
    assert "document:" in workflow


def test_render_github_header_comment() -> None:
    options = CiRenderOptions(ci="github")
    workflow = render_github(options)
    assert "Generated by OpenTide" in workflow
    assert "opentide setup ci github" in workflow


def test_gitlab_and_azure_deploy_jobs_fetch_full_history() -> None:
    """#348: inflight jobs already fetch history; deploy jobs must too."""
    from opentide.ci.azure import render_azure
    from opentide.ci.gitlab import render_gitlab

    gitlab = render_gitlab(CiRenderOptions(ci="gitlab", staging=True))
    production = gitlab.split("deploy_production:", 1)[1].split("\ndocument:", 1)[0]
    staging = gitlab.split("deploy_staging:", 1)[1].split("deploy_production:", 1)[0]
    validate = gitlab.split("\nvalidate:", 1)[1].split("\ngenerate:", 1)[0]
    assert 'GIT_DEPTH: "0"' in production
    assert 'GIT_DEPTH: "0"' in staging
    assert "GIT_DEPTH" not in validate

    azure = render_azure(CiRenderOptions(ci="azure", staging=True, default_branch="main"))
    prod = azure.split("- job: deploy_production", 1)[1].split("- job:", 1)[0]
    stage = azure.split("- job: deploy_staging", 1)[1].split("- job:", 1)[0]
    validate_job = azure.split("- job: validate\n", 1)[1].split("- job:", 1)[0]
    assert "fetchDepth: 0" in prod
    assert "fetchDepth: 0" in stage
    assert "fetchDepth" not in validate_job


def test_render_github_explorer_pages_jobs() -> None:
    options = CiRenderOptions(ci="github", explorer_pages=True, default_branch="main")
    workflow = render_github(options)
    assert "permissions:" in workflow
    assert "pages: write" in workflow
    assert "explorer:" in workflow
    assert "deploy-explorer:" in workflow
    # The bundle is exported by `opentide generate explorer` and handed to the
    # checked-out explorer repo; there is no `opentide explorer build` (#202).
    assert "opentide --json generate explorer" in workflow
    assert "OPENTIDE_BUNDLE" in workflow
    assert "opentide explorer build" not in workflow
    assert "actions/deploy-pages@v4" in workflow
    assert "concurrency:" in workflow
    assert "HAS_GITHUB_APP" in workflow
    assert "if: ${{ env.HAS_GITHUB_APP == 'true' }}" in workflow
    assert "secrets.GH_APP_ID && secrets.GH_APP_KEY" not in workflow.split("if:")[1:]
