"""Tests for GitHub Actions workflow rendering."""

from __future__ import annotations

from opentide.ci.github import render_github
from opentide.ci.models import CiRenderOptions


def test_render_github_includes_core_jobs() -> None:
    options = CiRenderOptions(
        ci="github",
        platforms=["sentinel", "crowdstrike"],
        default_branch="development",
        python_version="3.12",
    )
    workflow = render_github(options)
    assert "name: OpenTide" in workflow
    assert "validate:" in workflow
    assert "generate:" in workflow
    assert "deploy_production:" in workflow
    assert "document:" in workflow
    assert "branches:" in workflow
    assert "- development" in workflow


def test_render_github_validate_includes_query_platforms() -> None:
    options = CiRenderOptions(ci="github", platforms=["sentinel", "splunk"])
    workflow = render_github(options)
    assert "opentide validate query --platform sentinel" in workflow
    assert "opentide validate query --platform splunk" in workflow


def test_render_github_staging_job_when_enabled() -> None:
    options = CiRenderOptions(ci="github", staging=True)
    workflow = render_github(options)
    assert "deploy_staging:" in workflow
    assert "opentide deploy --plan STAGING" in workflow
    assert "needs: deploy_staging" in workflow


def test_render_github_no_staging_skips_staging_job() -> None:
    options = CiRenderOptions(ci="github", staging=False, promotion=False)
    workflow = render_github(options)
    assert "deploy_staging:" not in workflow
    assert "needs: generate" in workflow


def test_render_github_inflight_job_when_enabled() -> None:
    options = CiRenderOptions(ci="github", inflight=True, default_branch="main")
    workflow = render_github(options)
    assert "inflight_shards:" in workflow
    assert "inflight_prune:" in workflow
    assert "opentide generate inflight" in workflow
    assert "opentide generate inflight prune" in workflow
    assert 'git push origin "HEAD:main"' in workflow


def test_render_github_no_inflight_skips_inflight_job() -> None:
    options = CiRenderOptions(ci="github", inflight=False)
    workflow = render_github(options)
    assert "inflight_shards:" not in workflow


def test_render_github_promotion_job_omitted_when_no_steps() -> None:
    options = CiRenderOptions(ci="github", promotion=True, promotion_target="PRODUCTION")
    workflow = render_github(options)
    assert "promote:" not in workflow
    assert "opentide mutate promote" not in workflow


def test_render_github_sets_repo_root_without_optional_jobs() -> None:
    """Every generated workflow must export OPENTIDE_REPO_ROOT, even without explorer/inflight."""
    options = CiRenderOptions(ci="github", inflight=False, explorer_pages=False)
    workflow = render_github(options)
    preamble, _, jobs = workflow.partition("\njobs:")
    assert "OPENTIDE_REPO_ROOT: ${{ github.workspace }}" in preamble
    assert "OPENTIDE_REPO_ROOT" not in jobs
    assert "validate:" in workflow
    assert "generate:" in workflow
    assert "deploy_production:" in workflow
    assert "document:" in workflow


def test_render_github_header_comment() -> None:
    options = CiRenderOptions(ci="github")
    workflow = render_github(options)
    assert "Generated by OpenTide" in workflow
    assert "opentide setup ci github" in workflow


def test_render_github_explorer_pages_jobs() -> None:
    options = CiRenderOptions(ci="github", explorer_pages=True, default_branch="main")
    workflow = render_github(options)
    assert "permissions:" in workflow
    assert "pages: write" in workflow
    assert "explorer:" in workflow
    assert "deploy-explorer:" in workflow
    assert "OPENTIDE_EXPLORER_PATH" in workflow
    assert "actions/deploy-pages@v4" in workflow
    assert "concurrency:" in workflow
    assert "HAS_GITHUB_APP" in workflow
    assert "if: ${{ env.HAS_GITHUB_APP == 'true' }}" in workflow
    assert "secrets.GH_APP_ID && secrets.GH_APP_KEY" not in workflow.split("if:")[1:]
