"""Tests for GitHub Actions workflow rendering."""

from __future__ import annotations

from opentide.ci.github import render_github
from opentide.ci.models import CiRenderOptions


def test_render_github_includes_core_jobs() -> None:
    options = CiRenderOptions(
        ci="github",
        platforms=["sentinel", "crowdstrike"],
        default_branch="development",
        python_version="3.12",
    )
    workflow = render_github(options)
    assert "name: OpenTide" in workflow
    assert "validate:" in workflow
    assert "generate:" in workflow
    assert "deploy_production:" in workflow
    assert "document:" in workflow
    assert "branches:" in workflow
    assert "- development" in workflow


def test_render_github_validate_includes_query_platforms() -> None:
    options = CiRenderOptions(ci="github", platforms=["sentinel", "splunk"])
    workflow = render_github(options)
    assert "opentide validate query --platform sentinel" in workflow
    assert "opentide validate query --platform splunk" in workflow


def test_render_github_staging_job_when_enabled() -> None:
    options = CiRenderOptions(ci="github", staging=True)
    workflow = render_github(options)
    assert "deploy_staging:" in workflow
    assert "opentide deploy --plan STAGING" in workflow
    assert "needs: deploy_staging" in workflow


def test_render_github_no_staging_skips_staging_job() -> None:
    options = CiRenderOptions(ci="github", staging=False, promotion=False)
    workflow = render_github(options)
    assert "deploy_staging:" not in workflow
    assert "needs: generate" in workflow


def test_render_github_promotion_job() -> None:
    options = CiRenderOptions(ci="github", promotion=True, promotion_target="PRODUCTION")
    workflow = render_github(options)
    assert "promote:" in workflow
    assert "opentide mutate promote --target PRODUCTION" in workflow


def test_render_github_header_comment() -> None:
    options = CiRenderOptions(ci="github")
    workflow = render_github(options)
    assert "Generated by OpenTide" in workflow
    assert "opentide setup ci --ci github" in workflow
