steps:
  - template: ../templates/coretide_initialization.yml
  - script: |
      set -a
      source $(Pipeline.Workspace)/.env
      set +a
      cd coretide/Orchestration
      python deploy.py
    env: 
      DEPLOYMENT_PLAN: STAGING
    displayName: Deployment Routine
  - script: | 
      rm -rf coretide
    displayName: Remove CoreTide Repository
  - script: |
      changes=$(git status --porcelain)
      if [[ -z "$changes" ]]; then
        echo "No changes, exiting"
        exit 0
      fi

      filtered_changes=$(echo "$changes" | grep -vE '^(M|A|D) $(Build.Repository.Name)/|^(M|A|D) CoreTide/')
      if [[ -z "$filtered_changes" ]]; then
        echo "Changes only in Local Instance or CoreTide directories, not committing"
        exit 0
      fi

      echo "Updated files, committing"
      git add -- ':!$(Build.Repository.Name)' ':!CoreTide'
      git commit -m "Rule ID [skip ci]"
      git push origin "HEAD:$(System.PullRequest.SourceBranch)"
    displayName: Commit New Rule ID