"""Configure validate-on-commit hooks for detection repositories."""

from __future__ import annotations

import json
import os
import shlex
import subprocess
from dataclasses import dataclass
from pathlib import Path

import structlog
import yaml

from opentide.core.io import parse_yaml
from opentide.registry.discovery import OPENTIDE_DIR

logger = structlog.get_logger("opentide.cli.services.setup.hooks")

HOOK_ID = "opentide-validate"
HOOK_MARKER = "opentide-setup-hooks"
PRE_COMMIT_CONFIG_PATH = ".pre-commit-config.yaml"
VERSIONED_HOOK_PATH = f"{OPENTIDE_DIR}/hooks/pre-commit"
GIT_HOOK_PATH = ".git/hooks/pre-commit"

#: ``opentide validate`` resolves its tree from ``OPENTIDE_REPO_ROOT`` before it
#: looks at the working directory, and ``.env.example`` tells users to export
#: that variable. A hook that does not pin ``--repo`` therefore validates
#: whichever repository the shell last pointed at and lets broken YAML through.
_TOP_LEVEL = "$(git rev-parse --show-toplevel)"


def _workspace_word(relative: str) -> str:
    """Shell word naming the workspace: the Git root, plus *relative* when nested.

    Git and pre-commit run hooks from the Git root. A workspace in a
    subdirectory has to be named below it, or ``validate --strict`` checks a
    tree with no objects and passes.
    """
    top = f'"{_TOP_LEVEL}"'
    return top if not relative else f"{top}/{shlex.quote(relative)}"


def hook_entry(relative: str = "") -> str:
    """The pre-commit ``entry`` command for a workspace *relative* to the Git root."""
    return "sh -c " + shlex.quote(f"opentide --repo {_workspace_word(relative)} validate --strict")


def _yaml_value(value: str) -> str:
    """*value* as a YAML scalar; ``": "`` or ``" #"`` would end a plain one early."""
    return json.dumps(value) if ": " in value or " #" in value else value


HOOK_ENTRY = hook_entry()


def pre_commit_config(relative: str = "") -> str:
    return f"""\
# Generated by OpenTide. Re-run `opentide setup hooks` to refresh.
repos:
{local_hook_block(relative)}"""


def local_hook_block(relative: str = "") -> str:
    return f"""\
  - repo: local
    hooks:
      - id: opentide-validate
        name: opentide validate
        entry: {_yaml_value(hook_entry(relative))}
        language: system
        pass_filenames: false
        always_run: true
"""


def pre_commit_script(relative: str = "") -> str:
    nested = (
        f'OPENTIDE_HOOK_REPO="$OPENTIDE_HOOK_REPO"/{shlex.quote(relative)}\n' if relative else ""
    )
    return f"""\
#!/bin/sh
# opentide-setup-hooks: validate detection objects before commit.
# Generated by OpenTide. Re-run `opentide setup hooks` to refresh.
set -e
if [ -n "${{OPENTIDE_SKIP_HOOKS:-}}" ]; then
  exit 0
fi
if ! command -v opentide >/dev/null 2>&1; then
  echo "opentide not found on PATH. Install the package or set OPENTIDE_SKIP_HOOKS=1 to bypass." >&2
  exit 1
fi
# Validate the worktree being committed, not whatever OPENTIDE_REPO_ROOT names.
OPENTIDE_HOOK_REPO={_TOP_LEVEL}
{nested}exec opentide --repo "$OPENTIDE_HOOK_REPO" validate --strict
"""


PRE_COMMIT_CONFIG = pre_commit_config()
LOCAL_HOOK_BLOCK = local_hook_block()
PRE_COMMIT_SCRIPT = pre_commit_script()


@dataclass
class HooksSetupOptions:
    """Non-interactive Git hook setup."""

    path: Path = Path(".")
    install: bool = True
    yes: bool = False


@dataclass(frozen=True)
class _GitLayout:
    """Where the repository that contains a workspace keeps its root and hooks."""

    top_level: Path
    hooks_dir: Path
    #: Workspace path below ``top_level``; empty when the workspace is the root.
    relative: str


def _git_layout(target: Path) -> _GitLayout | None:
    """Ask Git, so nested workspaces, linked worktrees and ``core.hooksPath`` work.

    Looking for ``<workspace>/.git`` missed every workspace below the Git root
    and reported it as "Not a Git repository".
    """
    try:
        probe = subprocess.run(
            ["git", "-C", str(target), "rev-parse", "--show-toplevel", "--git-path", "hooks"],
            capture_output=True,
            text=True,
            check=False,
        )
    except OSError:
        return None
    lines = probe.stdout.splitlines()
    if probe.returncode != 0 or len(lines) != 2:
        return None
    top_level = Path(lines[0]).resolve()
    try:
        relative = target.resolve().relative_to(top_level).as_posix()
    except ValueError:
        return None
    return _GitLayout(
        top_level=top_level,
        hooks_dir=(target / lines[1]).resolve(),
        relative="" if relative == "." else relative,
    )


#: Entries written before the hook pinned ``--repo``; refreshed in place so an
#: upgrade actually fixes the tree the hook validates.
LEGACY_HOOK_ENTRIES = ("entry: opentide validate --strict",)


def _config_has_hook(text: str) -> bool:
    return f"id: {HOOK_ID}" in text


def _refresh_hook_entry(text: str, relative: str = "") -> str | None:
    """Rewrite a stale ``entry:`` line, or ``None`` when nothing needs changing.

    A nested workspace also replaces the root-pinned entry, which named the
    Git root rather than the workspace.
    """
    current = f"entry: {_yaml_value(hook_entry(relative))}"
    stale = [*LEGACY_HOOK_ENTRIES, f"entry: {HOOK_ENTRY}"] if relative else LEGACY_HOOK_ENTRIES
    for legacy in stale:
        if legacy in text:
            return text.replace(legacy, current)
    return None


def _write_executable(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    path.chmod(path.stat().st_mode | 0o111)


def _ensure_pre_commit_config(
    target: Path, warnings: list[str], relative: str = ""
) -> tuple[str, bool]:
    dest = target / PRE_COMMIT_CONFIG_PATH
    if not dest.is_file():
        dest.write_text(pre_commit_config(relative), encoding="utf-8")
        return PRE_COMMIT_CONFIG_PATH, True
    text = dest.read_text(encoding="utf-8")
    if _config_has_hook(text):
        refreshed = _refresh_hook_entry(text, relative)
        if refreshed is None:
            return PRE_COMMIT_CONFIG_PATH, False
        dest.write_text(refreshed, encoding="utf-8")
        return PRE_COMMIT_CONFIG_PATH, True
    try:
        parsed: object = parse_yaml(text) if text.strip() else {}
    except yaml.YAMLError:
        warnings.append(
            f"{PRE_COMMIT_CONFIG_PATH} is not valid YAML; left unchanged. "
            "Add a local opentide-validate hook manually."
        )
        return PRE_COMMIT_CONFIG_PATH, False
    if parsed is not None and not isinstance(parsed, dict):
        warnings.append(
            f"{PRE_COMMIT_CONFIG_PATH} is not a mapping; left unchanged. "
            "Add a local opentide-validate hook manually."
        )
        return PRE_COMMIT_CONFIG_PATH, False
    repos = parsed.get("repos") if isinstance(parsed, dict) else None
    if not repos:
        dest.write_text(pre_commit_config(relative), encoding="utf-8")
        return PRE_COMMIT_CONFIG_PATH, True
    suffix = "" if text.endswith("\n") else "\n"
    dest.write_text(text + suffix + local_hook_block(relative), encoding="utf-8")
    return PRE_COMMIT_CONFIG_PATH, True


def _ensure_versioned_hook(target: Path, relative: str = "") -> tuple[str, bool]:
    dest = target / VERSIONED_HOOK_PATH
    script = pre_commit_script(relative)
    existing = dest.read_text(encoding="utf-8") if dest.is_file() else None
    if existing == script:
        if os.access(dest, os.X_OK):
            return VERSIONED_HOOK_PATH, False
        dest.chmod(dest.stat().st_mode | 0o111)
        return VERSIONED_HOOK_PATH, True
    _write_executable(dest, script)
    return VERSIONED_HOOK_PATH, True


def _is_managed_hook(text: str) -> bool:
    return HOOK_MARKER in text


def _install_git_hook(
    target: Path, layout: _GitLayout | None, warnings: list[str]
) -> tuple[str | None, bool]:
    if layout is None:
        warnings.append("Not a Git repository; wrote hook files without installing .git/hooks.")
        return None, False
    dest = layout.hooks_dir / "pre-commit"
    shown = Path(os.path.relpath(dest, target)).as_posix()
    script = pre_commit_script(layout.relative)
    if dest.is_file():
        existing = dest.read_text(encoding="utf-8")
        if not _is_managed_hook(existing):
            warnings.append(
                f"{shown} already exists and is not an OpenTide hook; "
                "left unchanged. Use pre-commit or install the versioned hook manually."
            )
            return shown, False
        if existing == script and os.access(dest, os.X_OK):
            return shown, False
    _write_executable(dest, script)
    return shown, True


def run_hooks_setup(options: HooksSetupOptions) -> dict[str, object]:
    """Write pre-commit config and a validate-on-commit hook."""
    target = options.path.resolve()
    target.mkdir(parents=True, exist_ok=True)
    layout = _git_layout(target)
    relative = layout.relative if layout else ""
    warnings: list[str] = []
    written: list[str] = []
    skipped: list[str] = []
    for path, changed in (
        _ensure_pre_commit_config(target, warnings, relative),
        _ensure_versioned_hook(target, relative),
    ):
        if changed:
            written.append(path)
        else:
            skipped.append(path)
    if layout is not None and relative:
        warnings.append(
            f"pre-commit only reads .pre-commit-config.yaml at the repository root "
            f"({layout.top_level}); copy the opentide-validate hook there to use pre-commit."
        )
    installed = False
    if options.install:
        path, changed = _install_git_hook(target, layout, warnings)
        if path and changed:
            written.append(path)
            installed = True
        elif path:
            skipped.append(path)
    logger.debug(
        "hooks_setup",
        path=str(target),
        written=written,
        skipped=skipped,
        installed=installed,
    )
    result: dict[str, object] = {
        "message": "Validate-on-commit hooks configured",
        "path": str(target),
        "files": written,
        "skipped": skipped,
        "installed": installed,
    }
    if warnings:
        result["warnings"] = warnings
    return result
