"""Configure validate-on-commit hooks for detection repositories."""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path

import structlog
import yaml

from opentide.core.io import parse_yaml
from opentide.registry.discovery import OPENTIDE_DIR

logger = structlog.get_logger("opentide.cli.services.setup.hooks")

HOOK_ID = "opentide-validate"
HOOK_MARKER = "opentide-setup-hooks"
PRE_COMMIT_CONFIG_PATH = ".pre-commit-config.yaml"
VERSIONED_HOOK_PATH = f"{OPENTIDE_DIR}/hooks/pre-commit"
GIT_HOOK_PATH = ".git/hooks/pre-commit"

PRE_COMMIT_CONFIG = """\
# Generated by OpenTide. Re-run `opentide setup hooks` to refresh.
repos:
  - repo: local
    hooks:
      - id: opentide-validate
        name: opentide validate
        entry: opentide validate --strict
        language: system
        pass_filenames: false
        always_run: true
"""

LOCAL_HOOK_BLOCK = """\
  - repo: local
    hooks:
      - id: opentide-validate
        name: opentide validate
        entry: opentide validate --strict
        language: system
        pass_filenames: false
        always_run: true
"""

PRE_COMMIT_SCRIPT = """\
#!/bin/sh
# opentide-setup-hooks: validate detection objects before commit.
# Generated by OpenTide. Re-run `opentide setup hooks` to refresh.
set -e
if [ -n "${OPENTIDE_SKIP_HOOKS:-}" ]; then
  exit 0
fi
if ! command -v opentide >/dev/null 2>&1; then
  echo "opentide not found on PATH. Install the package or set OPENTIDE_SKIP_HOOKS=1 to bypass." >&2
  exit 1
fi
opentide validate --strict
"""


@dataclass
class HooksSetupOptions:
    """Non-interactive Git hook setup."""

    path: Path = Path(".")
    install: bool = True
    yes: bool = False


def _config_has_hook(text: str) -> bool:
    return f"id: {HOOK_ID}" in text


def _write_executable(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    path.chmod(path.stat().st_mode | 0o111)


def _ensure_pre_commit_config(target: Path, warnings: list[str]) -> tuple[str, bool]:
    dest = target / PRE_COMMIT_CONFIG_PATH
    if not dest.is_file():
        dest.write_text(PRE_COMMIT_CONFIG, encoding="utf-8")
        return PRE_COMMIT_CONFIG_PATH, True
    text = dest.read_text(encoding="utf-8")
    if _config_has_hook(text):
        return PRE_COMMIT_CONFIG_PATH, False
    try:
        parsed: object = parse_yaml(text) if text.strip() else {}
    except yaml.YAMLError:
        warnings.append(
            f"{PRE_COMMIT_CONFIG_PATH} is not valid YAML; left unchanged. "
            "Add a local opentide-validate hook manually."
        )
        return PRE_COMMIT_CONFIG_PATH, False
    if parsed is not None and not isinstance(parsed, dict):
        warnings.append(
            f"{PRE_COMMIT_CONFIG_PATH} is not a mapping; left unchanged. "
            "Add a local opentide-validate hook manually."
        )
        return PRE_COMMIT_CONFIG_PATH, False
    repos = parsed.get("repos") if isinstance(parsed, dict) else None
    if not repos:
        dest.write_text(PRE_COMMIT_CONFIG, encoding="utf-8")
        return PRE_COMMIT_CONFIG_PATH, True
    suffix = "" if text.endswith("\n") else "\n"
    dest.write_text(text + suffix + LOCAL_HOOK_BLOCK, encoding="utf-8")
    return PRE_COMMIT_CONFIG_PATH, True


def _ensure_versioned_hook(target: Path) -> tuple[str, bool]:
    dest = target / VERSIONED_HOOK_PATH
    existing = dest.read_text(encoding="utf-8") if dest.is_file() else None
    if existing == PRE_COMMIT_SCRIPT:
        if os.access(dest, os.X_OK):
            return VERSIONED_HOOK_PATH, False
        dest.chmod(dest.stat().st_mode | 0o111)
        return VERSIONED_HOOK_PATH, True
    _write_executable(dest, PRE_COMMIT_SCRIPT)
    return VERSIONED_HOOK_PATH, True


def _git_hooks_dir(target: Path) -> Path | None:
    git_dir = target / ".git"
    if git_dir.is_dir():
        return git_dir / "hooks"
    return None


def _is_managed_hook(text: str) -> bool:
    return HOOK_MARKER in text


def _install_git_hook(target: Path, warnings: list[str]) -> tuple[str | None, bool]:
    hooks_dir = _git_hooks_dir(target)
    if hooks_dir is None:
        warnings.append("Not a Git repository; wrote hook files without installing .git/hooks.")
        return None, False
    dest = hooks_dir / "pre-commit"
    if dest.is_file():
        existing = dest.read_text(encoding="utf-8")
        if not _is_managed_hook(existing):
            warnings.append(
                f"{GIT_HOOK_PATH} already exists and is not an OpenTide hook; "
                "left unchanged. Use pre-commit or install the versioned hook manually."
            )
            return GIT_HOOK_PATH, False
        if existing == PRE_COMMIT_SCRIPT and os.access(dest, os.X_OK):
            return GIT_HOOK_PATH, False
    _write_executable(dest, PRE_COMMIT_SCRIPT)
    return GIT_HOOK_PATH, True


def run_hooks_setup(options: HooksSetupOptions) -> dict[str, object]:
    """Write pre-commit config and a validate-on-commit hook."""
    target = options.path.resolve()
    target.mkdir(parents=True, exist_ok=True)
    warnings: list[str] = []
    written: list[str] = []
    skipped: list[str] = []
    for relative, changed in (
        _ensure_pre_commit_config(target, warnings),
        _ensure_versioned_hook(target),
    ):
        if changed:
            written.append(relative)
        else:
            skipped.append(relative)
    installed = False
    if options.install:
        relative, changed = _install_git_hook(target, warnings)
        if relative and changed:
            written.append(relative)
            installed = True
        elif relative:
            skipped.append(relative)
    logger.debug(
        "hooks_setup",
        path=str(target),
        written=written,
        skipped=skipped,
        installed=installed,
    )
    result: dict[str, object] = {
        "message": "Validate-on-commit hooks configured",
        "path": str(target),
        "files": written,
        "skipped": skipped,
        "installed": installed,
    }
    if warnings:
        result["warnings"] = warnings
    return result
