"""Configure validate-on-commit hooks for detection repositories."""

from __future__ import annotations

import json
import os
import re
import shlex
import subprocess
from dataclasses import dataclass
from pathlib import Path

import structlog
import yaml

from opentide.core.io import parse_yaml
from opentide.registry.discovery import OPENTIDE_DIR, is_opentide_workspace

logger = structlog.get_logger("opentide.cli.services.setup.hooks")

HOOK_ID = "opentide-validate"
HOOK_MARKER = "opentide-setup-hooks"
PRE_COMMIT_CONFIG_PATH = ".pre-commit-config.yaml"
VERSIONED_HOOK_PATH = f"{OPENTIDE_DIR}/hooks/pre-commit"
GIT_HOOK_PATH = ".git/hooks/pre-commit"

#: ``opentide validate`` resolves its tree from ``OPENTIDE_REPO_ROOT`` before it
#: looks at the working directory, and ``.env.example`` tells users to export
#: that variable. A hook that does not pin ``--repo`` therefore validates
#: whichever repository the shell last pointed at and lets broken YAML through.
_TOP_LEVEL = "$(git rev-parse --show-toplevel)"


def _workspace_word(relative: str) -> str:
    """Shell word naming the workspace: the Git root, plus *relative* when nested.

    Git and pre-commit run hooks from the Git root. A workspace in a
    subdirectory has to be named below it, or ``validate --strict`` checks a
    tree with no objects and passes.
    """
    top = f'"{_TOP_LEVEL}"'
    return top if not relative else f"{top}/{shlex.quote(relative)}"


def _workspace_label(relative: str) -> str:
    return relative or "the repository root"


def hook_entry(relative: str = "") -> str:
    """The pre-commit ``entry`` command for a workspace *relative* to the Git root.

    ``validate --strict`` passes on a directory without ``.opentide/``, so a
    pin left behind by a moved or renamed workspace would pass every commit.
    """
    script = (
        f"repo={_workspace_word(relative)}; "
        f'if [ ! -d "$repo/{OPENTIDE_DIR}" ]; then '
        f'echo "No OpenTide workspace at $repo (missing {OPENTIDE_DIR}/). '
        f'Re-run opentide setup hooks, or set SKIP={HOOK_ID} to bypass." >&2; exit 1; fi; '
        'exec opentide --repo "$repo" validate --strict'
    )
    return "sh -c " + shlex.quote(script)


def _yaml_value(value: str) -> str:
    """*value* as a YAML scalar that reads back unchanged.

    A plain scalar ends early at ``": "``, ``" #"`` or a tab before ``#``,
    breaks at a newline, and changes meaning after a leading indicator such
    as ``&`` or ``-``. JSON is a valid double-quoted YAML scalar.
    """
    candidates = [json.dumps(value, ensure_ascii=False), json.dumps(value)]
    if not any(char in value for char in "\t\r\n"):
        candidates.insert(0, value)
    for candidate in candidates:
        try:
            if yaml.safe_load(f"entry: {candidate}") == {"entry": value}:
                return candidate
        except yaml.YAMLError:
            continue
    return json.dumps(value)


HOOK_ENTRY = hook_entry()


def pre_commit_config(relative: str = "") -> str:
    return f"""\
# Generated by OpenTide. Re-run `opentide setup hooks` to refresh.
repos:
{local_hook_block(relative)}"""


def local_hook_block(relative: str = "") -> str:
    return f"""\
  - repo: local
    hooks:
      - id: opentide-validate
        name: opentide validate
        entry: {_yaml_value(hook_entry(relative))}
        language: system
        pass_filenames: false
        always_run: true
"""


#: ``validate --strict`` passes on a missing or empty directory; a hook still
#: pinned to a moved workspace has to fail instead of passing every commit.
_MISSING_WORKSPACE = (
    f"No OpenTide workspace at $OPENTIDE_HOOK_REPO (missing {OPENTIDE_DIR}/). "
    "Re-run 'opentide setup hooks' or set OPENTIDE_SKIP_HOOKS=1 to bypass."
)


#: One line per validated workspace, JSON-encoded so no path can end the comment.
_WORKSPACE_MARKER = "# opentide-workspace: "


def pre_commit_script(*workspaces: str) -> str:
    """Hook script validating each of *workspaces* (relative to the Git root; ``""`` is the root).

    A repository has a single ``pre-commit`` hook, so it has to cover every
    workspace set up in it. Every workspace is validated even after one fails,
    so a commit reports all of its problems at once.
    """
    pinned = workspaces or ("",)
    markers = "".join(f"{_WORKSPACE_MARKER}{json.dumps(w or '.')}\n" for w in pinned)
    words = " ".join(shlex.quote(w or ".") for w in pinned)
    return f"""\
#!/bin/sh
# opentide-setup-hooks: validate detection objects before commit.
# Generated by OpenTide. Re-run `opentide setup hooks` to refresh.
{markers}set -e
if [ -n "${{OPENTIDE_SKIP_HOOKS:-}}" ]; then
  exit 0
fi
if ! command -v opentide >/dev/null 2>&1; then
  echo "opentide not found on PATH. Install the package or set OPENTIDE_SKIP_HOOKS=1 to bypass." >&2
  exit 1
fi
# Validate the worktree being committed, not whatever OPENTIDE_REPO_ROOT names.
OPENTIDE_HOOK_TOP={_TOP_LEVEL}
OPENTIDE_HOOK_STATUS=0
for OPENTIDE_HOOK_WORKSPACE in {words}; do
  if [ "$OPENTIDE_HOOK_WORKSPACE" = . ]; then
    OPENTIDE_HOOK_REPO=$OPENTIDE_HOOK_TOP
  else
    OPENTIDE_HOOK_REPO=$OPENTIDE_HOOK_TOP/$OPENTIDE_HOOK_WORKSPACE
  fi
  if [ ! -d "$OPENTIDE_HOOK_REPO/{OPENTIDE_DIR}" ]; then
    echo "{_MISSING_WORKSPACE}" >&2
    OPENTIDE_HOOK_STATUS=1
  elif ! opentide --repo "$OPENTIDE_HOOK_REPO" validate --strict; then
    OPENTIDE_HOOK_STATUS=1
  fi
done
exit "$OPENTIDE_HOOK_STATUS"
"""


PRE_COMMIT_CONFIG = pre_commit_config()
LOCAL_HOOK_BLOCK = local_hook_block()
PRE_COMMIT_SCRIPT = pre_commit_script()


@dataclass
class HooksSetupOptions:
    """Non-interactive Git hook setup."""

    path: Path = Path(".")
    install: bool = True
    yes: bool = False


@dataclass(frozen=True)
class _GitLayout:
    """Where the repository that contains a workspace keeps its root and hooks."""

    top_level: Path
    hooks_dir: Path
    #: Workspace path below ``top_level``; empty when the workspace is the root.
    relative: str


def _git_layout(target: Path) -> _GitLayout | None:
    """Ask Git, so nested workspaces, linked worktrees and ``core.hooksPath`` work.

    Looking for ``<workspace>/.git`` missed every workspace below the Git root
    and reported it as "Not a Git repository".
    """
    try:
        probe = subprocess.run(
            ["git", "-C", str(target), "rev-parse", "--show-toplevel", "--git-path", "hooks"],
            capture_output=True,
            text=True,
            check=False,
        )
    except OSError:
        return None
    lines = probe.stdout.splitlines()
    if probe.returncode != 0 or len(lines) != 2:
        return None
    top_level = Path(lines[0]).resolve()
    try:
        relative = target.resolve().relative_to(top_level).as_posix()
    except ValueError:
        return None
    return _GitLayout(
        top_level=top_level,
        hooks_dir=(target / lines[1]).resolve(),
        relative="" if relative == "." else relative,
    )


#: Entries written before the hook pinned ``--repo``; refreshed in place so an
#: upgrade actually fixes the tree the hook validates.
LEGACY_HOOK_ENTRIES = ("opentide validate --strict",)

_ENTRY_LINE = re.compile(r"^(?P<lead>\s*(?:-\s+)?entry:[ \t]*)(?P<value>.*?)[ \t]*$")


def _config_has_hook(text: str) -> bool:
    return f"id: {HOOK_ID}" in text


def _entry_pin(entry: str) -> str | None:
    """The workspace an OpenTide ``entry`` pins: ``""`` for the Git root, ``None`` if not ours."""
    try:
        outer = shlex.split(entry)
        if len(outer) != 3 or outer[:2] != ["sh", "-c"]:
            return None
        lexer = shlex.shlex(outer[2], posix=True, punctuation_chars=True)
        lexer.whitespace_split = True
        words = list(lexer)
    except ValueError:
        return None
    if not {"opentide", "validate", "--strict"} <= set(words):
        return None
    for word in words:
        pin = word.removeprefix("repo=")
        if pin == _TOP_LEVEL:
            return ""
        if pin.startswith(f"{_TOP_LEVEL}/"):
            return pin[len(_TOP_LEVEL) + 1 :]
    return None


def _entry_value(raw: str) -> str | None:
    try:
        value = yaml.safe_load(raw)
    except yaml.YAMLError:
        return None
    return value if isinstance(value, str) else None


def _refresh_hook_entry(
    text: str, relative: str = "", top_level: Path | None = None
) -> tuple[str | None, list[str]]:
    """Point stale OpenTide ``entry:`` lines at *relative*.

    Returns the new text (``None`` when nothing changed) and the other
    workspaces that entries were left pinned to.

    Stale means unpinned, or pinned to *relative* in an older form without
    the missing-workspace guard. In a nested workspace's own config (no
    *top_level*) a Git-root pin is stale too: it named the root, not the
    workspace. In the config pre-commit reads (*top_level* given) a pin to
    another workspace belongs to that workspace and is kept, unless it no
    longer exists.
    """
    current = hook_entry(relative)
    lines = text.splitlines(keepends=True)
    changed = False
    kept: list[str] = []
    for index, line in enumerate(lines):
        body = line.rstrip("\r\n")
        match = _ENTRY_LINE.match(body)
        value = _entry_value(match["value"]) if match else None
        if match is None or value is None or value == current:
            continue
        pin = relative if value in LEGACY_HOOK_ENTRIES else _entry_pin(value)
        if pin is None:
            continue
        if pin != relative:
            if top_level is None:
                if pin:
                    continue
            elif is_opentide_workspace(top_level / pin):
                kept.append(pin)
                continue
        lines[index] = f"{match['lead']}{_yaml_value(current)}{line[len(body) :]}"
        changed = True
    return ("".join(lines) if changed else None), kept


def _kept_pin_warning(shown: str, pin: str, relative: str) -> str:
    return (
        f"{shown} runs {HOOK_ID} for {_workspace_label(pin)}; left unchanged, "
        f"so pre-commit does not validate {_workspace_label(relative)}."
    )


def _write_executable(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    path.chmod(path.stat().st_mode | 0o111)


def _ensure_pre_commit_config(
    target: Path, warnings: list[str], relative: str = ""
) -> tuple[str, bool]:
    dest = target / PRE_COMMIT_CONFIG_PATH
    if not dest.is_file():
        dest.write_text(pre_commit_config(relative), encoding="utf-8")
        return PRE_COMMIT_CONFIG_PATH, True
    text = dest.read_text(encoding="utf-8")
    if _config_has_hook(text):
        refreshed, kept = _refresh_hook_entry(text, relative, None if relative else target)
        warnings.extend(_kept_pin_warning(PRE_COMMIT_CONFIG_PATH, pin, relative) for pin in kept)
        if refreshed is None:
            return PRE_COMMIT_CONFIG_PATH, False
        dest.write_text(refreshed, encoding="utf-8")
        return PRE_COMMIT_CONFIG_PATH, True
    try:
        parsed: object = parse_yaml(text) if text.strip() else {}
    except yaml.YAMLError:
        warnings.append(
            f"{PRE_COMMIT_CONFIG_PATH} is not valid YAML; left unchanged. "
            "Add a local opentide-validate hook manually."
        )
        return PRE_COMMIT_CONFIG_PATH, False
    if parsed is not None and not isinstance(parsed, dict):
        warnings.append(
            f"{PRE_COMMIT_CONFIG_PATH} is not a mapping; left unchanged. "
            "Add a local opentide-validate hook manually."
        )
        return PRE_COMMIT_CONFIG_PATH, False
    repos = parsed.get("repos") if isinstance(parsed, dict) else None
    if not repos:
        dest.write_text(pre_commit_config(relative), encoding="utf-8")
        return PRE_COMMIT_CONFIG_PATH, True
    suffix = "" if text.endswith("\n") else "\n"
    dest.write_text(text + suffix + local_hook_block(relative), encoding="utf-8")
    return PRE_COMMIT_CONFIG_PATH, True


def _refresh_root_pre_commit_config(
    target: Path, layout: _GitLayout, warnings: list[str]
) -> tuple[str | None, bool]:
    """Point the repository root's OpenTide hook at a nested workspace.

    pre-commit reads only the root config, so a stale entry there validated
    the root, which has no objects, while the workspace's own entry was never run.
    """
    dest = layout.top_level / PRE_COMMIT_CONFIG_PATH
    text = dest.read_text(encoding="utf-8") if dest.is_file() else ""
    if not _config_has_hook(text):
        warnings.append(
            f"pre-commit only reads .pre-commit-config.yaml at the repository root "
            f"({layout.top_level}); copy the opentide-validate hook there to use pre-commit."
        )
        return None, False
    shown = Path(os.path.relpath(dest, target)).as_posix()
    refreshed, kept = _refresh_hook_entry(text, layout.relative, layout.top_level)
    warnings.extend(_kept_pin_warning(shown, pin, layout.relative) for pin in kept)
    if refreshed is None:
        return shown, False
    dest.write_text(refreshed, encoding="utf-8")
    return shown, True


def _ensure_versioned_hook(target: Path, relative: str = "") -> tuple[str, bool]:
    dest = target / VERSIONED_HOOK_PATH
    script = pre_commit_script(relative)
    existing = dest.read_text(encoding="utf-8") if dest.is_file() else None
    if existing == script:
        if os.access(dest, os.X_OK):
            return VERSIONED_HOOK_PATH, False
        dest.chmod(dest.stat().st_mode | 0o111)
        return VERSIONED_HOOK_PATH, True
    _write_executable(dest, script)
    return VERSIONED_HOOK_PATH, True


def _is_managed_hook(text: str) -> bool:
    return HOOK_MARKER in text


#: Hooks written before the marker lines pinned a nested workspace on this line.
_PREVIOUS_NESTED_PIN = 'OPENTIDE_HOOK_REPO="$OPENTIDE_HOOK_REPO"/'


def _hook_workspaces(script: str) -> list[str]:
    """Workspaces a managed hook validates, in order; ``""`` is the Git root."""
    lines = script.splitlines()
    pinned: list[str] = []
    for line in lines:
        if not line.startswith(_WORKSPACE_MARKER):
            continue
        try:
            value = json.loads(line.removeprefix(_WORKSPACE_MARKER))
        except ValueError:
            continue
        if isinstance(value, str):
            pinned.append("" if value == "." else value)
    if pinned:
        return pinned
    for line in lines:
        if line.startswith(_PREVIOUS_NESTED_PIN):
            try:
                return shlex.split(line.removeprefix(_PREVIOUS_NESTED_PIN))[:1]
            except ValueError:
                return []
    return [""] if "validate --strict" in script else []


def _hook_workspaces_after_setup(
    existing: str | None, layout: _GitLayout, shown: str, warnings: list[str]
) -> list[str]:
    """The workspaces already in the shared hook, then this one.

    Replacing the hook would silently stop validating every workspace set up
    before this one. A pinned workspace that lost its ``.opentide/`` makes the
    hook fail; re-running setup is how the user clears it, so it is dropped
    here, with a warning.
    """
    workspaces: list[str] = []
    for workspace in [*(_hook_workspaces(existing) if existing else []), layout.relative]:
        if workspace in workspaces:
            continue
        if workspace != layout.relative and not is_opentide_workspace(layout.top_level / workspace):
            warnings.append(
                f"{shown} no longer validates {_workspace_label(workspace)}: "
                f"it has no {OPENTIDE_DIR}/ directory."
            )
            continue
        workspaces.append(workspace)
    return workspaces


def _install_git_hook(
    target: Path, layout: _GitLayout | None, warnings: list[str]
) -> tuple[str | None, bool]:
    if layout is None:
        warnings.append("Not a Git repository; wrote hook files without installing .git/hooks.")
        return None, False
    dest = layout.hooks_dir / "pre-commit"
    shown = Path(os.path.relpath(dest, target)).as_posix()
    existing = dest.read_text(encoding="utf-8") if dest.is_file() else None
    if existing is not None and not _is_managed_hook(existing):
        warnings.append(
            f"{shown} already exists and is not an OpenTide hook; "
            "left unchanged. Use pre-commit or install the versioned hook manually."
        )
        return shown, False
    script = pre_commit_script(*_hook_workspaces_after_setup(existing, layout, shown, warnings))
    if existing == script and os.access(dest, os.X_OK):
        return shown, False
    _write_executable(dest, script)
    return shown, True


def run_hooks_setup(options: HooksSetupOptions) -> dict[str, object]:
    """Write pre-commit config and a validate-on-commit hook."""
    target = options.path.resolve()
    target.mkdir(parents=True, exist_ok=True)
    layout = _git_layout(target)
    relative = layout.relative if layout else ""
    warnings: list[str] = []
    written: list[str] = []
    skipped: list[str] = []
    for path, changed in (
        _ensure_pre_commit_config(target, warnings, relative),
        _ensure_versioned_hook(target, relative),
    ):
        if changed:
            written.append(path)
        else:
            skipped.append(path)
    if layout is not None and relative:
        root_config, changed = _refresh_root_pre_commit_config(target, layout, warnings)
        if root_config:
            (written if changed else skipped).append(root_config)
    installed = False
    if options.install:
        path, changed = _install_git_hook(target, layout, warnings)
        if path and changed:
            written.append(path)
            installed = True
        elif path:
            skipped.append(path)
    logger.debug(
        "hooks_setup",
        path=str(target),
        written=written,
        skipped=skipped,
        installed=installed,
    )
    result: dict[str, object] = {
        "message": "Validate-on-commit hooks configured",
        "path": str(target),
        "files": written,
        "skipped": skipped,
        "installed": installed,
    }
    if warnings:
        result["warnings"] = warnings
    return result
