"""Shared OpenTide CLI steps used across CI platform renderers."""

from __future__ import annotations

from opentide.ci.models import CiRenderOptions
from opentide.cli.enums import QUERY_VALIDATION_PLATFORMS


def pip_install(options: CiRenderOptions) -> str:
    return f'pip install "opentide>={options.opentide_version}"'


def query_platforms(options: CiRenderOptions) -> list[str]:
    return [p for p in options.platforms if p in QUERY_VALIDATION_PLATFORMS]


def core_cli_steps(options: CiRenderOptions) -> list[str]:
    """Validate and generate commands run after pip install."""
    steps = ["opentide validate"]
    for platform in query_platforms(options):
        steps.append(f"opentide validate query --platform {platform}")
    steps.append("opentide generate")
    return steps


def staging_deploy_steps(options: CiRenderOptions) -> list[str]:
    if not options.staging:
        return []
    return ["opentide deploy --plan STAGING"]


def production_deploy_steps(options: CiRenderOptions) -> list[str]:
    return ["opentide deploy --plan PRODUCTION"]


def promotion_steps(options: CiRenderOptions) -> list[str]:
    """Promotion runs inside ``opentide deploy`` pre-step; no separate mutate command."""
    return []


def document_steps(options: CiRenderOptions) -> list[str]:
    if not options.docs_enabled:
        return []
    return [f"opentide generate docs --output {options.docs_output}"]


def header_comment(options: CiRenderOptions) -> str:
    return (
        f"# Generated by OpenTide — regenerate with "
        f"`opentide setup ci {options.ci}`\n"
        "# Requires OPENTIDE_SECRETS and platform credentials in your CI secret store.\n"
    )
