objects = [ "tvm", "cdm", "dom", "mdr" ]

[paths.tide]
tvm = "Objects/Threat Vectors/"
dom = "Objects/Detection Objectives/"
cdm = "Objects/Detection Models/"
mdr = "Objects/Detection Rules/"
analytics = "Analytics/"
snippet_file = ".vscode/Model Templates.code-snippets"
json_schemas = "Schemas/"
templates = "Schemas/Templates/"
tide_indexes = "Schemas/Indexes/"
exports = "Schemas/Exports/"
custom_configurations = "Configurations/"

[paths.core]
staging_index_output = "staging_index.json"
index_output = "index.json"
vocabularies = "Framework/Vocabulary/"
configurations = "Configurations/"
metaschemas = "Framework/Meta Schemas/"
subschemas = "Framework/Meta Schemas/Sub Schemas/"
definitions = "Framework/Meta Schemas/Definitions/"
wiki_docs_folder = "wiki/"
models_docs_folder = "wiki/Models/"
schemas_docs_folder = "wiki/Framework/Schemas/"
vocabularies_docs = "wiki/Framework/Vocabularies/"
resources = "External/"

[indexes]
objects = "objects.json"
revisions = "revisions.json"

[exports]
attack_layer = "ATT&CK Navigator Layer.json"
table = "Objects Table.csv"

[metaschemas]
tvm = "Threat Vector.metaschema.yaml"
dom = "Detection Objective.metaschema.yaml"
cdm = "CDM Meta Schema.yaml"
mdr = "MDR Meta Schema.yaml"

[recomposition]
systems = "MDR Systems Deployment"

[config_metaschemas]
visibility = "Configurations/visibility.meta.yaml"

[config_json_schemas]
visibility = "Configurations/visibility.schema.json"

[json_schemas]
tvm = "TVM Schema.json"
dom = "Detection Objective.schema.json"
cdm = "CDM Schema.json"
mdr = "MDR Schema.json"

[data_fields]
tvm = "threat"
dom = "objective"
cdm = "detection"
mdr = "rule"

[templates]
tvm = "TVM TEMPLATE.yaml"
dom = "Detection Objective.template.yaml"
cdm = "CDM TEMPLATE.yaml"
mdr = "MDR TEMPLATE.yaml"
